// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v7.35.0
// source: proto/otel_sample.proto

package otelsamplev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_proto_otel_sample_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otel_sample_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_proto_otel_sample_proto_rawDescGZIP(), []int{0}
}

func (x *GetOrderRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int32                  `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Inventory     *GetInventoryResponse  `protobuf:"bytes,3,opt,name=inventory,proto3" json:"inventory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_proto_otel_sample_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otel_sample_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_proto_otel_sample_proto_rawDescGZIP(), []int{1}
}

func (x *GetOrderResponse) GetOrderId() int32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *GetOrderResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOrderResponse) GetInventory() *GetInventoryResponse {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type GetInventoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInventoryRequest) Reset() {
	*x = GetInventoryRequest{}
	mi := &file_proto_otel_sample_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryRequest) ProtoMessage() {}

func (x *GetInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otel_sample_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetInventoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_otel_sample_proto_rawDescGZIP(), []int{2}
}

func (x *GetInventoryRequest) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

type GetInventoryResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ItemId                  int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Available               int32                  `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	PostgresSource          string                 `protobuf:"bytes,3,opt,name=postgres_source,json=postgresSource,proto3" json:"postgres_source,omitempty"`
	ClickhouseRequestCount  int32                  `protobuf:"varint,4,opt,name=clickhouse_request_count,json=clickhouseRequestCount,proto3" json:"clickhouse_request_count,omitempty"`
	RedisCacheValue         string                 `protobuf:"bytes,5,opt,name=redis_cache_value,json=redisCacheValue,proto3" json:"redis_cache_value,omitempty"`
	RabbitmqDeliveryMessage string                 `protobuf:"bytes,6,opt,name=rabbitmq_delivery_message,json=rabbitmqDeliveryMessage,proto3" json:"rabbitmq_delivery_message,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *GetInventoryResponse) Reset() {
	*x = GetInventoryResponse{}
	mi := &file_proto_otel_sample_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInventoryResponse) ProtoMessage() {}

func (x *GetInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_otel_sample_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetInventoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_otel_sample_proto_rawDescGZIP(), []int{3}
}

func (x *GetInventoryResponse) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *GetInventoryResponse) GetAvailable() int32 {
	if x != nil {
		return x.Available
	}
	return 0
}

func (x *GetInventoryResponse) GetPostgresSource() string {
	if x != nil {
		return x.PostgresSource
	}
	return ""
}

func (x *GetInventoryResponse) GetClickhouseRequestCount() int32 {
	if x != nil {
		return x.ClickhouseRequestCount
	}
	return 0
}

func (x *GetInventoryResponse) GetRedisCacheValue() string {
	if x != nil {
		return x.RedisCacheValue
	}
	return ""
}

func (x *GetInventoryResponse) GetRabbitmqDeliveryMessage() string {
	if x != nil {
		return x.RabbitmqDeliveryMessage
	}
	return ""
}

var File_proto_otel_sample_proto protoreflect.FileDescriptor

const file_proto_otel_sample_proto_rawDesc = "" +
	"\n" +
	"\x17proto/otel_sample.proto\x12\rotelsample.v1\"*\n" +
	"\x0fGetOrderRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\"\x88\x01\n" +
	"\x10GetOrderResponse\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x05R\aorderId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12A\n" +
	"\tinventory\x18\x03 \x01(\v2#.otelsample.v1.GetInventoryResponseR\tinventory\".\n" +
	"\x13GetInventoryRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\"\x98\x02\n" +
	"\x14GetInventoryResponse\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\x05R\tavailable\x12'\n" +
	"\x0fpostgres_source\x18\x03 \x01(\tR\x0epostgresSource\x128\n" +
	"\x18clickhouse_request_count\x18\x04 \x01(\x05R\x16clickhouseRequestCount\x12*\n" +
	"\x11redis_cache_value\x18\x05 \x01(\tR\x0fredisCacheValue\x12:\n" +
	"\x19rabbitmq_delivery_message\x18\x06 \x01(\tR\x17rabbitmqDeliveryMessage2[\n" +
	"\fOrderService\x12K\n" +
	"\bGetOrder\x12\x1e.otelsample.v1.GetOrderRequest\x1a\x1f.otelsample.v1.GetOrderResponse2k\n" +
	"\x10InventoryService\x12W\n" +
	"\fGetInventory\x12\".otelsample.v1.GetInventoryRequest\x1a#.otelsample.v1.GetInventoryResponseBGZEgithub.com/enlinxu/otel-sample/go/code-based-instr/proto;otelsamplev1b\x06proto3"

var (
	file_proto_otel_sample_proto_rawDescOnce sync.Once
	file_proto_otel_sample_proto_rawDescData []byte
)

func file_proto_otel_sample_proto_rawDescGZIP() []byte {
	file_proto_otel_sample_proto_rawDescOnce.Do(func() {
		file_proto_otel_sample_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_otel_sample_proto_rawDesc), len(file_proto_otel_sample_proto_rawDesc)))
	})
	return file_proto_otel_sample_proto_rawDescData
}

var file_proto_otel_sample_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_otel_sample_proto_goTypes = []any{
	(*GetOrderRequest)(nil),      // 0: otelsample.v1.GetOrderRequest
	(*GetOrderResponse)(nil),     // 1: otelsample.v1.GetOrderResponse
	(*GetInventoryRequest)(nil),  // 2: otelsample.v1.GetInventoryRequest
	(*GetInventoryResponse)(nil), // 3: otelsample.v1.GetInventoryResponse
}
var file_proto_otel_sample_proto_depIdxs = []int32{
	3, // 0: otelsample.v1.GetOrderResponse.inventory:type_name -> otelsample.v1.GetInventoryResponse
	0, // 1: otelsample.v1.OrderService.GetOrder:input_type -> otelsample.v1.GetOrderRequest
	2, // 2: otelsample.v1.InventoryService.GetInventory:input_type -> otelsample.v1.GetInventoryRequest
	1, // 3: otelsample.v1.OrderService.GetOrder:output_type -> otelsample.v1.GetOrderResponse
	3, // 4: otelsample.v1.InventoryService.GetInventory:output_type -> otelsample.v1.GetInventoryResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_otel_sample_proto_init() }
func file_proto_otel_sample_proto_init() {
	if File_proto_otel_sample_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_otel_sample_proto_rawDesc), len(file_proto_otel_sample_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_otel_sample_proto_goTypes,
		DependencyIndexes: file_proto_otel_sample_proto_depIdxs,
		MessageInfos:      file_proto_otel_sample_proto_msgTypes,
	}.Build()
	File_proto_otel_sample_proto = out.File
	file_proto_otel_sample_proto_goTypes = nil
	file_proto_otel_sample_proto_depIdxs = nil
}
